from .depth_segm_net import DepthSegmNet
from .depth_only_segm_net import DepthOnlySegmNet
from .depth_init_segm_net import DepthInitSegmNet
from .depth_segm_attention_net import DepthSegmNetAttention
from .depth_segm_attention_net1 import DepthSegmNetAttention01
from .depth_segm_attention_net2 import DepthSegmNetAttention02
from .depth_segm_attention_net3 import DepthSegmNetAttention03
from .depth_segm_attention_net4 import DepthSegmNetAttention04
from .depth_segm_attention_net5 import DepthSegmNetAttention05
from .depth_segm_attention_net6 import DepthSegmNetAttention06
from .depth_segm_attention_net7 import DepthSegmNetAttention07
from .depth_segm_attention_net8 import DepthSegmNetAttention as DepthSegmNetAttention08
from .depth_segm_attention_net9 import DepthSegmNetAttention as DepthSegmNetAttention09
from .depth_segm_attention_net10 import DepthSegmNetAttention as DepthSegmNetAttention10
from .depth_segm_attention_net11 import DepthSegmNetAttention as DepthSegmNetAttention11
from .depth_segm_attention_net12 import DepthSegmNetAttention as DepthSegmNetAttention12
from .depth_segm_attention_net13 import DepthSegmNetAttention as DepthSegmNetAttention13


from .depth_segm_attention_net2_1 import DepthSegmNetAttention02 as DepthSegmNetAttention02_1
from .depth_segm_attention_net2_2 import DepthSegmNetAttention as DepthSegmNetAttention02_2
from .depth_segm_attention_net2_3 import DepthSegmNetAttention as DepthSegmNetAttention02_3
from .depth_segm_attention_net2_4 import DepthSegmNetAttention as DepthSegmNetAttention02_4
from .depth_segm_attention_net2_5 import DepthSegmNetAttention as DepthSegmNetAttention02_5
from .depth_segm_attention_net2_6 import DepthSegmNetAttention as DepthSegmNetAttention02_6
from .depth_segm_attention_net2_7 import DepthSegmNetAttention as DepthSegmNetAttention02_7
from .depth_segm_attention_net2_8 import DepthSegmNetAttention as DepthSegmNetAttention02_8
from .depth_segm_attention_net2_9 import DepthSegmNetAttention as DepthSegmNetAttention02_9

from .depth_segm_attention_net2_8DColormap import DepthSegmNetAttention as DepthSegmNetAttention02_8DC
from .depth_segm_attention_net2_8DC_Max import DepthSegmNetAttention as DepthSegmNetAttention02_8DC_Max
from .depth_segm_attention_net2_8DC_Sum import DepthSegmNetAttention as DepthSegmNetAttention02_8DC_Sum
#

# from .transformer import Transformer

from .depth_segm_RDFNet import DepthSegmNet as DepthSegmNet_RDF

from .depth_segm_A02_8MMF import DepthSegmNetAttention as DepthSegmNetAttention02_8MMF
from .depth_segm_A02_8MMF_MultiPrediction import DepthSegmNetAttention as DepthSegmNetAttention02_8MMF_MP

from .depth_segm_A02_8ACNet_MP import DepthSegmNetAttention as DepthSegmNetAttention02_8ACNet_MP
from .depth_segm_A02_8ACNet_MP_woBG import DepthSegmNetAttention as DepthSegmNetAttention02_8ACNet_MP_woBG

from .d3s_rgbd import SegmNet as D3S_RGBD
from .d3s_rgbd_CBAM import SegmNet as D3S_CBAM_RGBD
from .d3s_rgbd_CBAM02 import SegmNet as D3S_CBAM_RGBD02
from .d3s_rgbd_CBAM02_2 import SegmNet as D3S_CBAM_RGBD02_2
from .d3s_rgbd_CBAM03 import SegmNet as D3S_CBAM_RGBD03

from .d3s_rgbd_Attention import SegmNet as D3S_Attention_RGBD

from .d3s_rgbd_DWeight import SegmNet as D3S_DW_RGBD
from .d3s_rgbd_DW02 import SegmNet as D3S_DW02_RGBD
from .d3s_rgbd_DW03 import SegmNet as D3S_DW03_RGBD
from .d3s_rgbd_DW04 import SegmNet as D3S_DW04_RGBD 

from .d3s_rgbd_Attn_DW import SegmNet as D3S_Attn_DW_RGBD
from .d3s_rgbd_Attn02_DW import SegmNet as D3S_Attn02_DW_RGBD

from .d3s_rgbd_DWSim import SegmNet as D3S_DWSim_RGBD
from .d3s_rgbd_DIF import SegmNet as D3S_DIF_RGBD
from .d3s_rgbd_DIF02 import SegmNet as D3S_DIF02_RGBD
from .d3s_rgbd_DIF03 import SegmNet as D3S_DIF03_RGBD
from .d3s_rgbd_DIF04 import SegmNet as D3S_DIF04_RGBD
from .d3s_rgbd_DIF05 import SegmNet as D3S_DIF05_RGBD

from .d3s_rgbd_BBS import SegmNet as D3S_BBS_RGBD
