from .depth_segm_net import DepthSegmNet
from .depth_only_segm_net import DepthOnlySegmNet
from .depth_init_segm_net import DepthInitSegmNet
from .depth_segm_attention_net import DepthSegmNetAttention
